use super::stage_zero_model::{Filesystem, FrameLayout, Identifiers, Sequences};
use super::{StageZeroError, require};

/// Checks identifier representation, generation, and deduplication rules.
///
/// Binary IDs are fixed-width UUID bytes generated by the OS CSPRNG; textual
/// IDs are bounded UTF-8 bytes with no normalization or path interpretation.
pub(super) fn validate_identifiers(ids: &Identifiers) -> Result<(), StageZeroError> {
    require(
        ids.node_encoding == "uuid-v4-rfc4122-bytes",
        "node ID encoding mismatch",
    )?;
    require(ids.node_bytes == 16, "node ID width must be 16")?;
    require(
        ids.node_generator == "os_csprng",
        "node ID generator mismatch",
    )?;
    require(
        ids.node_persistence == "node.meta before first write",
        "node ID persistence rule mismatch",
    )?;
    require(ids.node_immutable, "node ID must be immutable")?;
    require(
        ids.transaction_encoding == "uuid-v4-rfc4122-bytes",
        "transaction ID encoding mismatch",
    )?;
    require(
        ids.transaction_bytes == 16,
        "transaction ID width must be 16",
    )?;
    require(
        ids.transaction_generator == "os_csprng",
        "transaction ID generator mismatch",
    )?;
    require(
        ids.transaction_reuse == "reject_if_exists",
        "transaction ID reuse rule mismatch",
    )?;
    require(
        ids.operation_encoding == "uuid-v4-rfc4122-bytes",
        "operation ID encoding mismatch",
    )?;
    require(ids.operation_bytes == 16, "operation ID width must be 16")?;
    require(
        ids.operation_generator == "os_csprng",
        "operation ID generator mismatch",
    )?;
    require(
        ids.operation_reuse == "reject_if_exists",
        "operation ID reuse rule mismatch",
    )?;
    require(
        ids.operation_dedup_key == "(origin_node_id, operation_id)",
        "operation deduplication key mismatch",
    )?;
    require(ids.text_encoding == "utf-8", "text ID encoding mismatch")?;
    require(ids.text_min_bytes == 1, "text ID minimum length must be 1")?;
    require(
        ids.text_max_bytes == 255,
        "text ID maximum length must be 255",
    )?;
    require(
        ids.text_length_prefix == "u16",
        "text ID length prefix must be u16",
    )?;
    require(
        ids.text_equality == "bytewise",
        "text ID equality must be bytewise",
    )?;
    require(
        ids.text_normalization == "none",
        "text ID normalization must be none",
    )?;
    require(
        ids.text_nul == "forbidden",
        "NUL must be forbidden in text IDs",
    )
}

/// Checks sequence allocation and contiguous cursor semantics.
///
/// Origin and partition sequences start at one and only durable commits may
/// advance them. A cursor starts at zero and advances one contiguous value at a
/// time; duplicates stay put and gaps remain pending.
pub(super) fn validate_sequences(sequences: &Sequences) -> Result<(), StageZeroError> {
    require(
        sequences.origin_scope == "(origin_node_id, dataset_id, partition_id)",
        "origin sequence scope mismatch",
    )?;
    require(
        sequences.origin_width_bits == 64,
        "origin sequence width must be 64",
    )?;
    require(
        sequences.origin_initial == 1,
        "origin sequence must start at 1",
    )?;
    require(
        sequences.origin_assignment == "after_durable_commit",
        "origin sequence assignment mismatch",
    )?;
    require(
        sequences.origin_persistence == "same_commit_durability_boundary",
        "origin sequence persistence mismatch",
    )?;
    require(
        sequences.origin_restart == "last_durable_plus_one",
        "origin sequence restart rule mismatch",
    )?;
    require(
        sequences.origin_overflow == "reject_E_SEQUENCE_EXHAUSTED",
        "origin sequence overflow rule mismatch",
    )?;
    require(
        sequences.partition_scope == "(dataset_id, partition_id)",
        "partition sequence scope mismatch",
    )?;
    require(
        sequences.partition_width_bits == 64,
        "partition sequence width must be 64",
    )?;
    require(
        sequences.partition_initial == 1,
        "partition sequence must start at 1",
    )?;
    require(
        sequences.partition_assignment == "at_durable_commit",
        "partition sequence assignment mismatch",
    )?;
    require(
        sequences.partition_gaps == "failed_transaction_does_not_advance",
        "partition sequence gap rule mismatch",
    )?;
    require(
        sequences.partition_overflow == "reject_E_SEQUENCE_EXHAUSTED",
        "partition sequence overflow rule mismatch",
    )?;
    require(
        sequences.cursor_key == "(peer_node_id, origin_node_id, dataset_id, partition_id, kind)",
        "cursor key mismatch",
    )?;
    require(
        sequences.cursor_kinds == ["send", "received", "applied"],
        "cursor kinds mismatch",
    )?;
    require(
        sequences.cursor_value == "largest_contiguous_durable_origin_sequence",
        "cursor value mismatch",
    )?;
    require(sequences.cursor_initial == 0, "cursor must start at zero")?;
    require(
        sequences.cursor_advance == "only_current_plus_one",
        "cursor advance rule mismatch",
    )?;
    require(
        sequences.duplicate_effect == "does_not_advance",
        "duplicate cursor effect mismatch",
    )?;
    require(
        sequences.gap_effect == "pending_E_SEQUENCE_GAP_and_does_not_advance",
        "gap cursor effect mismatch",
    )
}

/// Checks canonical path templates and atomic file replacement steps.
pub(super) fn validate_filesystem(filesystem: &Filesystem) -> Result<(), StageZeroError> {
    require(filesystem.data_root == "data", "data root mismatch")?;
    require(
        filesystem.format_meta == "format.meta",
        "format metadata name mismatch",
    )?;
    require(filesystem.lock_file == "LOCK", "lock file name mismatch")?;
    require(
        filesystem.partition_directory == "partitions/{partition_digest_hex}",
        "partition directory template mismatch",
    )?;
    require(
        filesystem.segment_pattern == "segments/segment-{first_sequence:020}.ldb",
        "segment path template mismatch",
    )?;
    require(
        filesystem.snapshot_pattern == "snapshots/snapshot-{commit_sequence:020}.lds",
        "snapshot path template mismatch",
    )?;
    require(
        filesystem.cursor_pattern == "cursors/{peer_node_id}.cur",
        "cursor path template mismatch",
    )?;
    require(
        filesystem.quarantine_pattern == "quarantine/{origin_node_id}-{origin_sequence:020}.bin",
        "quarantine path template mismatch",
    )?;
    require(
        filesystem.temporary_directory == "tmp",
        "temporary directory mismatch",
    )?;
    require(
        filesystem.temporary_suffix == ".partial",
        "temporary suffix mismatch",
    )?;
    require(
        filesystem.path_input_rule == "relative_only_reject_absolute_parent_and_separator",
        "path input rule mismatch",
    )?;
    require(
        filesystem.atomic_write_steps == ["write", "sync_file", "rename", "sync_parent_directory"],
        "atomic write steps mismatch",
    )
}

/// Checks the byte-exact 32-byte frame header and checksum policy.
pub(super) fn validate_frame_layout(layout: &FrameLayout) -> Result<(), StageZeroError> {
    require(layout.magic_offset == 0, "frame magic offset mismatch")?;
    require(layout.magic_width == 4, "frame magic width mismatch")?;
    require(layout.version_offset == 4, "frame version offset mismatch")?;
    require(layout.version_width == 2, "frame version width mismatch")?;
    require(layout.type_offset == 6, "frame type offset mismatch")?;
    require(layout.flags_offset == 7, "frame flags offset mismatch")?;
    require(
        layout.payload_length_offset == 8,
        "frame payload length offset mismatch",
    )?;
    require(
        layout.payload_length_width == 4,
        "frame payload length width mismatch",
    )?;
    require(
        layout.sequence_offset == 12,
        "frame sequence offset mismatch",
    )?;
    require(layout.sequence_width == 8, "frame sequence width mismatch")?;
    require(
        layout.checksum_offset == 20,
        "frame checksum offset mismatch",
    )?;
    require(layout.checksum_width == 4, "frame checksum width mismatch")?;
    require(
        layout.reserved_offset == 24,
        "frame reserved offset mismatch",
    )?;
    require(layout.reserved_width == 8, "frame reserved width mismatch")?;
    require(
        layout.reserved_value == 0,
        "frame reserved bytes must be zero",
    )?;
    require(
        layout.checksum_coverage == "header_without_checksum_field_plus_payload",
        "frame checksum coverage mismatch",
    )?;
    require(
        layout.unknown_type == "reject_E_FRAME_TYPE",
        "unknown frame type rule mismatch",
    )?;
    require(
        layout.nonzero_flags == "reject_E_FRAME_TYPE",
        "nonzero frame flags rule mismatch",
    )
}
